# Generated by Django 4.1.7 on 2023-03-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Company name')),
                ('img', models.ImageField(upload_to='images', verbose_name='logo')),
            ],
        ),
    ]
