# Generated by Django 4.1.7 on 2023-03-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Company name')),
                ('text', models.TextField(verbose_name='Text')),
                ('img', models.ImageField(upload_to='images', verbose_name='logo')),
            ],
        ),
    ]
