# Generated by Django 4.1.7 on 2023-03-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigname', models.CharField(max_length=60, verbose_name='Company name')),
                ('text', models.TextField(verbose_name='Text')),
                ('price', models.PositiveBigIntegerField(verbose_name='Price')),
                ('offer', models.TextField(verbose_name='Offer')),
            ],
        ),
    ]
