# Generated by Django 4.1.7 on 2023-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_price_offer_1_alter_price_offer_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Your name')),
                ('email', models.TextField(verbose_name='mail')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
